services:
  - type: web
    name: python-project-83
    runtime: python
    plan: free
    branch: main
    buildCommand: make install
    startCommand: .venv/bin/gunicorn page_analyzer:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: python-project-83-db
          property: connectionString

databases:
  - name: python-project-83-db
    plan: free
    databaseName: page_analyzer
    user: page_analyzer
