services:
  - type: web
    name: python-project-83
    runtime: python
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: .venv/bin/gunicorn page_analyzer:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: project-83-postgres
          property: connectionString
